check config error in status endpoint
fabric8-services/fabric8-env pull request #25
Opened 2019-01-18 11:45 UTC by nurali-techie

Fixes: https://github.com/fabric8-services/fabric8-env/issues/12

2019-01-18 13:25 UTC, xcoulon requested changes
looks good, but I think that you did not test all cases on config error. See https://github.com/fabric8-services/fabric8-cluster/blob/master/configuration/configuration_blackbox_test.go for something more exhaustive.

2019-01-18 13:25 UTC, xcoulon commented on configuration/configuration.go
> +	return fmt.Sprintf("%s\n", y)
it could be just `return string(y)` here

2019-01-19 04:38 UTC, nurali-techie commented on configuration/configuration.go
> +	return fmt.Sprintf("%s\n", y)
see there is `\n` due to which `Sprintf` is used.

2019-01-19 04:38 UTC, nurali-techie commented
@xcoulon thanks for the look, yup config_test is missed out.  Let me do that :+1:

2019-01-21 04:33 UTC, nurali-techie commented
@xcoulon I just checked in details and I see tests are provided for the changes.  This is the effective changes I have done in configuration.go file [changes_link](https://github.com/fabric8-services/fabric8-env/blob/6bae8bba766b7ec5bca13ec5beb83247c63e4a74/configuration/configuration.go#L71-L87) which mainly deal with setting/modifying configErr depending on different config_param value.  Against that I have provided these tests [test_file](https://github.com/fabric8-services/fabric8-env/blob/6bae8bba766b7ec5bca13ec5beb83247c63e4a74/controller/status_blackbox_test.go#L77-L105).  Test check, configErr when devMode=true and devMode=false.

I am not sure what other test I can add .. plz give me test_definition to help me understand.

2019-01-21 08:11 UTC, xcoulon commented on configuration/configuration.go
> +	return fmt.Sprintf("%s\n", y)
why do you need to add a `\n` here?

2019-01-21 08:15 UTC, xcoulon commented
> @xcoulon I just checked in details and I see tests are provided for the changes. This is the effective changes I have done in configuration.go file [changes_link](https://github.com/fabric8-services/fabric8-env/blob/6bae8bba766b7ec5bca13ec5beb83247c63e4a74/configuration/configuration.go#L71-L87) which mainly deal with setting/modifying configErr depending on different config_param value. Against that I have provided these tests [test_file](https://github.com/fabric8-services/fabric8-env/blob/6bae8bba766b7ec5bca13ec5beb83247c63e4a74/controller/status_blackbox_test.go#L77-L105). Test check, configErr when devMode=true and devMode=false.
> 
> I am not sure what other test I can add .. plz give me test_definition to help me understand.

@nurali-techie I think that it would be good if you could provide a set of tests to verify that the configuration reports an error in all cases that are covered by the code, that's all. The most straightforward way to do it would be in a `configuration_test.go`, not at the `status controller` level.

2019-01-21 10:22 UTC, nurali-techie commented on configuration/configuration.go
> +	return fmt.Sprintf("%s\n", y)
@xcoulon plz note, this method is not part of this PR change, I just moved it in this PR.
Previously, it was copied from f8-wit.  I also checked in f8-cluster, f8-auth, f8-tenant, all has this `\n`.

2019-01-21 10:54 UTC, nurali-techie commented
@xcoulon incorporate your review comment, kindly have a look.

2019-01-21 11:20 UTC, xcoulon approved these changes

2019-01-21 11:20 UTC, xcoulon commented
> @xcoulon incorporate your review comment, kindly have a look.

thanks for taking the time to add those tests, @nurali-techie! I just approved your PR

2019-01-21 14:08 UTC, merged